### ISSUE TITLE
make command error

### ISSUE THREAD

**Issue by kevintvh** [Jet1oeil/opendbviewer#13]
opendbviewer$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by N0un** [comment]
Please read our compilation instructions.

1. `./build.sh regen`
2. `make`

**Comment by kevintvh** [comment]
Ah sorry. The first command was failed as following:

> 
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_aea5e.dir/build.make:97: recipe for target 'cmTC_aea5e' failed
> make[1]: *** [cmTC_aea5e] Error 1
> make[1]: Leaving directory '/opt/dev/softs/databases/opendbviewer/CMakeFiles/CMakeTmp'
> Makefile:126: recipe for target 'cmTC_aea5e/fast' failed
> make: *** [cmTC_aea5e/fast] Error 2

**Comment by N0un** [comment]
Is it the trace produced by the `./build.sh regen` command? I think not... Be careful to execute this command in your `/opt/dev/softs/databases/opendbviewer` directory.

**Comment by kevintvh** [comment]
It is in /opt/dev/softs/databases/opendbviewer/CMakeFiles/CMakeError.log after the run first command. Which dir should I execute the command?

**Comment by N0un** [comment]
First, which is you OS?
Go to this cloned project directory (example: if you called `git clone ...` in `/dir/mydir`, then go to `/dir/mydir/opendbviewer`). Then, in this `opendbviewer` directory, please call `./build.sh regen` and copy the terminal displayed trace here.

**Comment by kevintvh** [comment]
It is Linux. Yes, that is correct directory. the errors were not about the directory, is it?

To reproduce:
1. Check out the code to any folder
2. Run below command inside code folder
./build.sh regen

Trace:
> /opt/dev/softs/databases/opendbviewer$ ./build.sh regen
> ...
> -- All required headers are found 
> -- Looking for strdup
> -- Looking for strdup - found
> -- Looking for strcasestr
> -- Looking for strcasestr - found
> -- Looking for strcasecmp
> -- Looking for strcasecmp - found
> -- Looking for strncasecmp
> -- Looking for strncasecmp - found
> -- Looking for _stricmp
> -- Looking for _stricmp - not found
> -- Looking for _strnicmp
> -- Looking for _strnicmp - not found
> -- Looking for strndup
> -- Looking for strndup - found
> -- Looking for strtok_r
> -- Looking for strtok_r - found
> -- Looking for abs
> -- Looking for abs - found
> -- All required functions are found
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Looking for Qt major version: 5
> CMake Warning at CMakeModules/IncludeLibraries.cmake:167 (find_package):
>   By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5LinguistTools", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5LinguistTools"
>   with any of the following names:
> 
>     Qt5LinguistToolsConfig.cmake
>     qt5linguisttools-config.cmake
> 
>   Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
>   set "Qt5LinguistTools_DIR" to a directory containing one of the above
>   files.  If "Qt5LinguistTools" provides a separate development package or
>   SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:128 (include)
> 
> 
> CMake Error at CMakeModules/IncludeLibraries.cmake:178 (message):
>   Qt5LinguistTools package is required
> Call Stack (most recent call first):
>   CMakeLists.txt:128 (include)
> 
> -- Configuring incomplete, errors occurred!
> See also "/opt/dev/softs/databases/opendbviewer/CMakeFiles/CMakeOutput.log".
> See also "/opt/dev/softs/databases/opendbviewer/C

MakeFiles/CMakeError.log".

**Comment by N0un** [comment]
Ok but which Linux are you using?

This step failed because some required packages are missing on your system. Please read this project's `README.md`. We explain in this file all the necessary steps to compile this project, including required packages installation on a Linux Debian based.

Command on Debian:
`sudo apt-get install qtbase5-dev qttools5-dev-tools libqt5sql5-sqlite libqt5sql5-mysql libqt5sql5-psql`

**Comment by kevintvh** [comment]
It is Ubuntu 18.04 LTS
Yes. I did follow the doc before submitting this ticket.

sudo apt-get install qtbase5-dev qttools5-dev-tools libqt5sql5-sqlite libqt5sql5-mysql libqt5sql5-psql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5sql5-sqlite is already the newest version (5.9.5+dfsg-0ubuntu1).
qtbase5-dev is already the newest version (5.9.5+dfsg-0ubuntu1).
libqt5sql5-mysql is already the newest version (5.9.5+dfsg-0ubuntu1).
libqt5sql5-psql is already the newest version (5.9.5+dfsg-0ubuntu1).
qttools5-dev-tools is already the newest version (5.9.5-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by N0un** [comment]
Maybe an other package is needed and we miss it in our documentation... Please try to install this package:
`sudo apt-get install qttools5-dev`
and retry.

**Comment by N0un** [comment]
No problem! :)
