### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by mrkaban** [Jet1oeil/opendbviewer#39]
Thanks for the free software licensed under the GNU GPL v3! I added your program to a large Russian-language site about free software for Windows, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/opendbviewer-prosmotr-baz-dannyh/).

I am ready to help with translation into Russian.

**Comment by SaiyanRiku** [comment]
Thank you very much for this. If you want to make russian translation, you can take the file : https://github.com/Jet1oeil/opendbviewer/blob/master/ts/fr.ts and replace all french translation with russian translation and send us. Regards

**Comment by mrkaban** [comment]
Write here when you publish the version with translation into Russian, as I will need to change the screenshot and the note about the interface language on the site.

[ru.zip](https://github.com/Jet1oeil/opendbviewer/files/6607903/ru.zip)

**Comment by SaiyanRiku** [comment]
Thank you, i added it in source code.

**Comment by SaiyanRiku** [comment]
Closed by commit 38e4024
