### ISSUE TITLE
Postgresql support  ?

### ISSUE THREAD

**Issue by obiwankennedy** [Jet1oeil/opendbviewer#4]
Do you plan to add Postgresql support ?

**Comment by N0un** [comment]
Everything is possible ;) For now, opendbviewer supports different SQL drivers based on these Qt implementation. As far as I know, Qt provides a driver for PostgreSQL so it should be very easy to integrate. If you want to collaborate with us to make this update (or others), you are welcome ! :)

**Comment by SaiyanRiku** [comment]
Done ;)
