### ISSUE TITLE
QSqlDatabase: QMYSQL driver not loaded

### ISSUE THREAD

**Issue by Nico207** [Jet1oeil/opendbviewer#8]
Hi, 

when I try to create a new connection, I get the following message :

```
Erreur de connexion
Impossible de se connecter à la base de donnée, veuillez vérifier les informations de connexion.
```

```
QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE
```

Windows 7 64bits
OpenDBViewer V1.0.2r833358

**Comment by N0un** [comment]
Hi! Thanks for reporting it. What is your Qt version?

**Comment by Nico207** [comment]
I just used the Windows installer.
I didn't install QT.

**Comment by N0un** [comment]
Ok I'll take a look soon.
